import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';
import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Kanji Dojo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				

			</div>
		</div>
	);
}
